export default {
  login: "ruanyf",
  id: 905434,
  node_id: "MDQ6VXNlcjkwNTQzNA==",
  avatar_url: "https://avatars0.githubusercontent.com/u/905434?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ruanyf",
  html_url: "https://github.com/ruanyf",
  followers_url: "https://api.github.com/users/ruanyf/followers",
  following_url: "https://api.github.com/users/ruanyf/following{/other_user}",
  gists_url: "https://api.github.com/users/ruanyf/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ruanyf/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ruanyf/subscriptions",
  organizations_url: "https://api.github.com/users/ruanyf/orgs",
  repos_url: "https://api.github.com/users/ruanyf/repos",
  events_url: "https://api.github.com/users/ruanyf/events{/privacy}",
  received_events_url: "https://api.github.com/users/ruanyf/received_events",
  type: "User",
  site_admin: false,
  name: "Ruan YiFeng",
  company: null,
  blog: "https://twitter.com/ruanyf",
  location: "Shanghai, China",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 64,
  public_gists: 27,
  followers: 62967,
  following: 0,
  created_at: "2011-07-10T01:07:17Z",
  updated_at: "2020-10-27T15:24:58Z"
};
